<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>RayTracer</RootNamespace>
    <AssemblyName>RayTracer</AssemblyName>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <ApplicationDefaultFont>9pt Segoe UI</ApplicationDefaultFont>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ApplicationVisualStyles>true</ApplicationVisualStyles>
    <ApplicationUseCompatibleTextRendering>false</ApplicationUseCompatibleTextRendering>
  </PropertyGroup>

</Project>
